version: '3.9'

networks:
  app-tier:
    driver: bridge

volumes:
  mongo:
    driver: local
  cache:
    driver: local

services:
  redis:
    image: redis:alpine
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - app-tier
  
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27017:27017
    networks:
      - app-tier
  
  api:
    depends_on:
      - redis
      - mongo
    build:
      context: .
      dockerfile: Api.Dockerfile
    ports:
      - 3100:3100
    links:
      - mongo
      - redis
    networks:
      - app-tier
  
  worker:
    depends_on:
      - redis
      - mongo
    build:
      context: .
      dockerfile: Processor.Dockerfile
    links:
      - mongo
      - redis
    networks:
      - app-tier
